CREATE TABLE IF NOT EXISTS `financial_transaction` (
    id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    category VARCHAR(40) NOT NULL,
    description VARCHAR(200),
    amount INTEGER,
    transaction_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );
